name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment (dev/prod)"
        required: true
        default: dev

jobs:
  plan-destroy:
    runs-on: [self-hosted]
    defaults:
      run:
        working-directory: ./live

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4


      - name: Terraform Init
        run: terraform init -backend-config=../env/${{ github.event.inputs.environment }}/backend.tfvars

      - name: Terraform Destroy Plan
        run: terraform plan -var-file=../env/${{ github.event.inputs.environment }}/main.tfvars -destroy -out=tfplan-destroy.out

      - name: Upload Destroy Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-destroy
          path: live/tfplan-destroy.out

  destroy:
    runs-on: [self-hosted]
    needs: plan-destroy
    environment: ${{ github.event.inputs.environment }}
    defaults:
      run:
        working-directory: ./live

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download Destroy Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan-destroy
          path: live

      - name: Terraform Init
        run: terraform init -backend-config=../env/${{ github.event.inputs.environment }}/backend.tfvars

      - name: Terraform Destroy Apply
        run: terraform apply -auto-approve tfplan-destroy.out
